### ISSUE TITLE
AttributeError: 'Flag' object has no attribute 'value'

### ISSUE THREAD

**Issue by damianoazzolini** [potassco/xorro#43]
Hi.
I'm trying xorro but, after installing with `setup.py` as shown in the `README.md` file, for every example I test i get the following error:
```
python3 -m xorro examples/test.lp 2 --sampling --s=4 --q=0.5
xorro version 1.0
Reading from examples/test.lp
Traceback (most recent call last):
  File "/home/damiano/.local/lib/python3.7/site-packages/clingo/application.py", line 293, in _pyclingo_application_main
    app.main(Control(control), [ _to_str(files[i]) for i in range(size) ])
  File "/mnt/c/Users/damia/Desktop/Ricerca/Repos/xorro/xorro/__init__.py", line 249, in main
    if self.__sampling.value:
AttributeError: 'Flag' object has no attribute 'value'
```

**Comment by pudumagico** [comment]
Installing python 3.6 and clingo 5.3 fixed that for me

**Comment by flavioeverardo** [comment]
Yes. There is work to do to update it to the current clingo and python versions. So far it works with previos clingo releases.
